### ISSUE TITLE
on almalinux 9.0 based node imgbased fails on missing file

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/imgbased#14]
**Describe the bug**
Reported initially in https://github.com/oVirt/ovirt-node-ng-image/issues/49#issuecomment-1152405279

`imgbase-setup.service` fails on missing `/usr/share/factory/etc/iscsi/initiatorname.iscsi`

**Screenshots**

![173080960-ae7f848b-2f9a-40b7-a284-f0ca61f7b44e](https://user-images.githubusercontent.com/937860/173101213-3297f77b-5608-4e1c-a5ca-943e3bce62ff.png)

**Comment by CygnusHyoga** [comment]
Hi, I have the same problem with centos 9 stream. I'm trying to ovirt node iso image with centros stream 9.
